# 1. 공통 로그 설정 정의
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  # 1. MySQL 데이터베이스 컨테이너
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    logging: *default-logging # 공통 로그 설정 재사용
    command:
      - --default-time-zone=+09:00
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      TZ: Asia/Seoul
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      # 컨테이너가 삭제되어도 DB 데이터가 유실되지 않도록 마운트
      - /home/ubuntu/app/mysql-data:/var/lib/mysql
    networks:
      - ecommerce-net
    # MySQL 컨테이너가 요청을 처리할 수 있는 상태인지 주기적으로 확인
    healthcheck:
      # 컨테이너 내부에서 실행할 상태 확인 명령. 정상적으로 접속해 SELECT 1을
      # 실행하면 헬스체크가 성공하고, 실패하면 MySQL이 아직 준비되지 않은 것으로 판단
      test: [ "CMD-SHELL", "mysql -u root -p'${MYSQL_ROOT_PASSWORD}' -e 'SELECT 1;'" ]
      # 헬스체크를 실행하는 주기
      interval: 5s
      # 한 번의 헬스체크 명령이 응답을 기다리는 최대 시간, 이 시간을 넘기면 실패로 간주
      timeout: 5s
      # 주어진 숫자만큼 연속으로 실패하면, 실패로 간주
      retries: 10
      # 컨테이너 시작 후 헬스체크 실패를 허용하는 초기 대기 시간
      start_period: 20s

  # 2. Spring Boot 백엔드 컨테이너
  backend:
    image: ${DOCKERHUB_USERNAME}/${DOCKER_IMAGE}:${DOCKER_TAG}
    container_name: ecommerce-backend-stage
    restart: unless-stopped
    logging: *default-logging # 공통 로그 설정 재사용
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      TZ: Asia/Seoul
      SPRING_PROFILES_ACTIVE: stage
      JAVA_OPTS: -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -Xms128m -Xmx256m
      # Docker 네트워크 내부에서는 서비스 이름(mysql-db)이 호스트명이 됩니다.
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      mysql-db:
        condition: service_healthy # MySQL 헬스체크 통과 후 백엔드 실행
    networks:
      - ecommerce-net

  nginx:
    image: nginx:alpine
    container_name: ecommerce-nginx
    restart: unless-stopped
    logging: *default-logging # 공통 로그 설정 재사용
    ports:
      - "100.75.142.26:80:80"
      - "100.75.142.26:443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - /etc/tailscale/certs:/etc/nginx/certs:ro
    depends_on:
      - backend
    networks:
      - ecommerce-net

  # ecommerce/docker-compose.yml 에 추가할 Promtail 예시
  promtail:
    image: grafana/promtail:2.9.0
    container_name: ecommerce-promtail
    restart: unless-stopped
    logging: *default-logging # 공통 로그 설정 재사용
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml:ro
    command: -config.file=/etc/promtail/promtail-config.yaml
    network_mode: host

networks:
  ecommerce-net:
    driver: bridge
