spring:
  datasource:
    # TODO: MYSQL_DB_HOST, MYSQL_DB_USERNAME, MYSQL_DB_PASSWORD 환경 변수 설정하고, 깃헙 secret에 올리기
    url: jdbc:mysql://${MYSQL_DB_HOST}/ecommerce?serverTimezone=Asia/Seoul
    username: ${MYSQL_DB_USERNAME}
    password: ${MYSQL_DB_PASSWORD}

server:
  port: 8080

springdoc:
  packages-to-scan: io.github.lsgeun
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
