version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ubuntu/app
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/deploy/stop.sh
      timeout: 120
      runas: ubuntu
  ApplicationStart:
    - location: scripts/deploy/start.sh
      timeout: 300
      runas: ubuntu
