server {
    listen 80;
    # 발급받은 DuckDNS 도메인 주소를 작성합니다.
    server_name lsgeun-ecommerce.duckdns.org;

    location / {
        # Docker network 내부에서 backend 컨테이너의 8080 포트로 전달
        proxy_pass http://backend:8080;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
