name: Main Build Test

on:
  pull_request:
    branches:
      - main

jobs:
  run-build-test:
    if: github.head_ref != 'infra/31-monorepo-settings'
    uses: ./.github/workflows/reusable-build-test.yaml
    secrets: inherit
