name: Main Build Test

on:
  pull_request:
    branches:
      - main
      - '!infra/31-monorepo-settings'

jobs:
  run-build-test:
    uses: ./.github/workflows/reusable-build-test.yaml
    secrets: inherit
