name: Temporary Infra, Build Test & Deploy to EC2

on:
  push:
    branches: [ infra/31-monorepo-settings ]

jobs:
  run-build-test:
    uses: ./.github/workflows/reusable-build-test.yaml
    secrets: inherit

  run-deploy:
    needs: run-build-test # CI 통과 후 CD 실행
    uses: ./.github/workflows/reusable-deploy.yaml
    secrets: inherit
